version: "3.9"

services:
  app:
    build:
      context: .
    container_name: app
    command:
      - "make"
      - "grun"
      - docker/run.sh
    ports:
      - "5000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      - database

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --port 6379


  database:
    image: postgres:16-alpine
    container_name: db_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  celery:
    build: .
    container_name: celery_django
    depends_on:
      - app
    env_file:
      - .env
    command: docker/celery.sh


